environment:
  matrix:
    - CMAKE_VERSION: "3.29.2"

branches:
  only:
    - master

image: Visual Studio 2022
configuration: Release
build:
  verbosity: detailed

clone_script:
  - git clone --recurse-submodules https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

install:
  # Download CMake installer
  - ps: |
        $url = "https://github.com/Kitware/CMake/releases/download/v$env:CMAKE_VERSION/cmake-$env:CMAKE_VERSION-windows-x86_64.msi"
        $destination = "C:\projects\cmake-$env:CMAKE_VERSION-windows-x86_64.msi"
        Invoke-WebRequest -Uri $url -OutFile $destination

  # Install CMake
  - ps: Start-Process -FilePath "msiexec" -ArgumentList "/i C:\projects\cmake-$env:CMAKE_VERSION-windows-x86_64.msi /quiet /qn /norestart /log install.log ADD_CMAKE_TO_PATH=System" -Wait -NoNewWindow

  # Update the PATH, just in case it's needed
  - SET PATH=C:\Program Files\CMake\bin;%PATH%
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  - appveyor DownloadFile https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/LLVM-16.0.6-win64.exe -FileName llvm-installer.exe
  - START /WAIT llvm-installer.exe /S /D=C:\"Program Files\LLVM"
  - dir C:\
  - dir C:\OpenSSL-v32-Win64
  - dir C:\OpenSSL-v32-Win64\bin
  - dir C:\OpenSSL-v32-Win64\lib
  - dir C:\OpenSSL-v32-Win64\lib\VC
  - dir C:\OpenSSL-v32-Win64\lib\VC\static

notifications:
  - provider: Email
    to:
      - patryk.czachurski@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

before_build:
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd C:\projects\hypersomnia

build_script:
  - cmake --version
  - cd cmake/steam_integration
  - mkdir build
  - cd build
  - cmake -DBUILD_STEAM=0 -DCMAKE_BUILD_TYPE=Release -G Ninja ..
  - ninja install
  - cd ../../..
  - mkdir nin
  - cd nin
  - mkdir %CONFIGURATION%
  - cd %CONFIGURATION%
  - cmake -G Ninja -DLINK_STEAM_INTEGRATION=1 -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_LINKER=lld-link -DARCHITECTURE="x64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DOUTPUT_TO_HYPERSOMNIA_FOLDER=1 -DOPENSSL_ROOT_DIR=C:\OpenSSL-v32-Win64 ../..
  - ninja

test_script:
  - cd ../../hypersomnia
  - ps: '& ../cmake/test_pack_upload.ps1 -configuration $env:CONFIGURATION -console_mode 0'

